name:                refract-replica
version:             0.1.0.0
github:              "githubuser/refract-replica"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/refract-replica#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- replica
- stm
- text
- transformers
- wai
- wai-websockets
- websockets
- warp

library:
  source-dirs: src

executables:
  refract-replica-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - refract-replica
    - aeson-optics
    - bytestring
    - foreign-store
    - optics
    - pretty-simple
    - unordered-containers
    - vector

tests:
  refract-replica-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - refract-replica
